<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>Alik.VGEMechanoidSignalFix</AssemblyName>
    <RootNamespace>Alik.VGE.MechanoidSignalFix</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" />
  </ItemGroup>
</Project>
